#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PracticaQuinto")]
	public partial class LinqConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Rol(Tbl_Rol instance);
    partial void UpdateTbl_Rol(Tbl_Rol instance);
    partial void DeleteTbl_Rol(Tbl_Rol instance);
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    #endregion
		
		public LinqConexionDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.PracticaQuintoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Rol> Tbl_Rol
		{
			get
			{
				return this.GetTable<Tbl_Rol>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Rol")]
	public partial class Tbl_Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rol;
		
		private string _nombre_rol;
		
		private string _estado_rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    partial void Onnombre_rolChanging(string value);
    partial void Onnombre_rolChanged();
    partial void Onestado_rolChanging(string value);
    partial void Onestado_rolChanged();
    #endregion
		
		public Tbl_Rol()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_rol
		{
			get
			{
				return this._nombre_rol;
			}
			set
			{
				if ((this._nombre_rol != value))
				{
					this.Onnombre_rolChanging(value);
					this.SendPropertyChanging();
					this._nombre_rol = value;
					this.SendPropertyChanged("nombre_rol");
					this.Onnombre_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string estado_rol
		{
			get
			{
				return this._estado_rol;
			}
			set
			{
				if ((this._estado_rol != value))
				{
					this.Onestado_rolChanging(value);
					this.SendPropertyChanging();
					this._estado_rol = value;
					this.SendPropertyChanged("estado_rol");
					this.Onestado_rolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _cedula_usu;
		
		private string _nombre_usu;
		
		private string _direccion_usu;
		
		private string _telefono_usu_;
		
		private string _correo_usu;
		
		private string _usuario_usu;
		
		private string _contrasenia_usu;
		
		private string _salt_contrasenia_usu;
		
		private System.Nullable<int> _recupero_contrasenia_usu;
		
		private int _rol_usu;
		
		private string _foto_usu;
		
		private System.Nullable<System.DateTime> _fechacreacion_usu;
		
		private string _estado_usu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Oncedula_usuChanging(string value);
    partial void Oncedula_usuChanged();
    partial void Onnombre_usuChanging(string value);
    partial void Onnombre_usuChanged();
    partial void Ondireccion_usuChanging(string value);
    partial void Ondireccion_usuChanged();
    partial void Ontelefono_usu_Changing(string value);
    partial void Ontelefono_usu_Changed();
    partial void Oncorreo_usuChanging(string value);
    partial void Oncorreo_usuChanged();
    partial void Onusuario_usuChanging(string value);
    partial void Onusuario_usuChanged();
    partial void Oncontrasenia_usuChanging(string value);
    partial void Oncontrasenia_usuChanged();
    partial void Onsalt_contrasenia_usuChanging(string value);
    partial void Onsalt_contrasenia_usuChanged();
    partial void Onrecupero_contrasenia_usuChanging(System.Nullable<int> value);
    partial void Onrecupero_contrasenia_usuChanged();
    partial void Onrol_usuChanging(int value);
    partial void Onrol_usuChanged();
    partial void Onfoto_usuChanging(string value);
    partial void Onfoto_usuChanged();
    partial void Onfechacreacion_usuChanging(System.Nullable<System.DateTime> value);
    partial void Onfechacreacion_usuChanged();
    partial void Onestado_usuChanging(string value);
    partial void Onestado_usuChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_usu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cedula_usu
		{
			get
			{
				return this._cedula_usu;
			}
			set
			{
				if ((this._cedula_usu != value))
				{
					this.Oncedula_usuChanging(value);
					this.SendPropertyChanging();
					this._cedula_usu = value;
					this.SendPropertyChanged("cedula_usu");
					this.Oncedula_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usu
		{
			get
			{
				return this._nombre_usu;
			}
			set
			{
				if ((this._nombre_usu != value))
				{
					this.Onnombre_usuChanging(value);
					this.SendPropertyChanging();
					this._nombre_usu = value;
					this.SendPropertyChanged("nombre_usu");
					this.Onnombre_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_usu", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string direccion_usu
		{
			get
			{
				return this._direccion_usu;
			}
			set
			{
				if ((this._direccion_usu != value))
				{
					this.Ondireccion_usuChanging(value);
					this.SendPropertyChanging();
					this._direccion_usu = value;
					this.SendPropertyChanged("direccion_usu");
					this.Ondireccion_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_usu_", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telefono_usu_
		{
			get
			{
				return this._telefono_usu_;
			}
			set
			{
				if ((this._telefono_usu_ != value))
				{
					this.Ontelefono_usu_Changing(value);
					this.SendPropertyChanging();
					this._telefono_usu_ = value;
					this.SendPropertyChanged("telefono_usu_");
					this.Ontelefono_usu_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_usu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correo_usu
		{
			get
			{
				return this._correo_usu;
			}
			set
			{
				if ((this._correo_usu != value))
				{
					this.Oncorreo_usuChanging(value);
					this.SendPropertyChanging();
					this._correo_usu = value;
					this.SendPropertyChanged("correo_usu");
					this.Oncorreo_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_usu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario_usu
		{
			get
			{
				return this._usuario_usu;
			}
			set
			{
				if ((this._usuario_usu != value))
				{
					this.Onusuario_usuChanging(value);
					this.SendPropertyChanging();
					this._usuario_usu = value;
					this.SendPropertyChanged("usuario_usu");
					this.Onusuario_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia_usu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string contrasenia_usu
		{
			get
			{
				return this._contrasenia_usu;
			}
			set
			{
				if ((this._contrasenia_usu != value))
				{
					this.Oncontrasenia_usuChanging(value);
					this.SendPropertyChanging();
					this._contrasenia_usu = value;
					this.SendPropertyChanged("contrasenia_usu");
					this.Oncontrasenia_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salt_contrasenia_usu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string salt_contrasenia_usu
		{
			get
			{
				return this._salt_contrasenia_usu;
			}
			set
			{
				if ((this._salt_contrasenia_usu != value))
				{
					this.Onsalt_contrasenia_usuChanging(value);
					this.SendPropertyChanging();
					this._salt_contrasenia_usu = value;
					this.SendPropertyChanged("salt_contrasenia_usu");
					this.Onsalt_contrasenia_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recupero_contrasenia_usu", DbType="Int")]
		public System.Nullable<int> recupero_contrasenia_usu
		{
			get
			{
				return this._recupero_contrasenia_usu;
			}
			set
			{
				if ((this._recupero_contrasenia_usu != value))
				{
					this.Onrecupero_contrasenia_usuChanging(value);
					this.SendPropertyChanging();
					this._recupero_contrasenia_usu = value;
					this.SendPropertyChanged("recupero_contrasenia_usu");
					this.Onrecupero_contrasenia_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_usu", DbType="Int NOT NULL")]
		public int rol_usu
		{
			get
			{
				return this._rol_usu;
			}
			set
			{
				if ((this._rol_usu != value))
				{
					this.Onrol_usuChanging(value);
					this.SendPropertyChanging();
					this._rol_usu = value;
					this.SendPropertyChanged("rol_usu");
					this.Onrol_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_usu", DbType="VarChar(100)")]
		public string foto_usu
		{
			get
			{
				return this._foto_usu;
			}
			set
			{
				if ((this._foto_usu != value))
				{
					this.Onfoto_usuChanging(value);
					this.SendPropertyChanging();
					this._foto_usu = value;
					this.SendPropertyChanged("foto_usu");
					this.Onfoto_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechacreacion_usu", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechacreacion_usu
		{
			get
			{
				return this._fechacreacion_usu;
			}
			set
			{
				if ((this._fechacreacion_usu != value))
				{
					this.Onfechacreacion_usuChanging(value);
					this.SendPropertyChanging();
					this._fechacreacion_usu = value;
					this.SendPropertyChanged("fechacreacion_usu");
					this.Onfechacreacion_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_usu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string estado_usu
		{
			get
			{
				return this._estado_usu;
			}
			set
			{
				if ((this._estado_usu != value))
				{
					this.Onestado_usuChanging(value);
					this.SendPropertyChanging();
					this._estado_usu = value;
					this.SendPropertyChanged("estado_usu");
					this.Onestado_usuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
